# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jan 13 01:22:58 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(2400, 1800))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.topFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topFrame.sizePolicy().hasHeightForWidth())
        self.topFrame.setSizePolicy(sizePolicy)
        self.topFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.topFrame.setObjectName(_fromUtf8("topFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.topFrame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.explorerFrame = QtGui.QFrame(self.topFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.explorerFrame.sizePolicy().hasHeightForWidth())
        self.explorerFrame.setSizePolicy(sizePolicy)
        self.explorerFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.explorerFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.explorerFrame.setObjectName(_fromUtf8("explorerFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.explorerFrame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.dicomData = QtGui.QTableWidget(self.explorerFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dicomData.sizePolicy().hasHeightForWidth())
        self.dicomData.setSizePolicy(sizePolicy)
        self.dicomData.setObjectName(_fromUtf8("dicomData"))
        self.dicomData.setColumnCount(0)
        self.dicomData.setRowCount(0)
        self.verticalLayout_4.addWidget(self.dicomData)
        self.horizontalLayout_2.addWidget(self.explorerFrame)
        self.dicomFrame = QtGui.QFrame(self.topFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dicomFrame.sizePolicy().hasHeightForWidth())
        self.dicomFrame.setSizePolicy(sizePolicy)
        self.dicomFrame.setMinimumSize(QtCore.QSize(600, 400))
        self.dicomFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.dicomFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.dicomFrame.setLineWidth(0)
        self.dicomFrame.setObjectName(_fromUtf8("dicomFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dicomFrame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dicomLayout = QtGui.QGridLayout()
        self.dicomLayout.setObjectName(_fromUtf8("dicomLayout"))
        self.sliderFrame = QtGui.QFrame(self.dicomFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderFrame.sizePolicy().hasHeightForWidth())
        self.sliderFrame.setSizePolicy(sizePolicy)
        self.sliderFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.sliderFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sliderFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sliderFrame.setLineWidth(0)
        self.sliderFrame.setObjectName(_fromUtf8("sliderFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.sliderFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sliderLayout = QtGui.QHBoxLayout()
        self.sliderLayout.setObjectName(_fromUtf8("sliderLayout"))
        self.dicomSlider = QtGui.QSlider(self.sliderFrame)
        self.dicomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dicomSlider.setObjectName(_fromUtf8("dicomSlider"))
        self.sliderLayout.addWidget(self.dicomSlider)
        self.playButton = QtGui.QPushButton(self.sliderFrame)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.sliderLayout.addWidget(self.playButton)
        self.horizontalLayout.addLayout(self.sliderLayout)
        self.dicomLayout.addWidget(self.sliderFrame, 1, 0, 1, 1)
        self.imageFrame = QtGui.QFrame(self.dicomFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFrame.sizePolicy().hasHeightForWidth())
        self.imageFrame.setSizePolicy(sizePolicy)
        self.imageFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.imageFrame.setLineWidth(0)
        self.imageFrame.setObjectName(_fromUtf8("imageFrame"))
        self.gridLayout = QtGui.QGridLayout(self.imageFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.imageLayout = QtGui.QGridLayout()
        self.imageLayout.setObjectName(_fromUtf8("imageLayout"))
        self.gridLayout.addLayout(self.imageLayout, 0, 0, 1, 1)
        self.dicomLayout.addWidget(self.imageFrame, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.dicomLayout)
        self.horizontalLayout_2.addWidget(self.dicomFrame)
        self.verticalLayout.addWidget(self.topFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.playButton.setText(_translate("MainWindow", "Play", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionLoad.setText(_translate("MainWindow", "Load..", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSave.setText(_translate("MainWindow", "Save..", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))

